### ISSUE TITLE
Codice Assembly Hiding

### ISSUE THREAD

**Issue by SpaceCowboyS01** [SpaceCowboyS01/DekketScris#8]
**Istruzioni Assembly per la crittografia da implementare nel linguaggio C**
- [x] Lettura di un carattere in byte
- [x] Scomposizione del byte
- [x] Modifica dell'ultimo bit del byte x-esimo dell'immagine

**Comment by SpaceCowboyS01** [comment]
Manca l'assembly
Attendo aggiornamenti perr concludere la issue

**Comment by SpaceCowboyS01** [comment]
`void hiding(File image, File text, File out) {
image.seek(10);
int offset = 0;
image.read(&offset, sizeof(offset));

image.seek(0);
for (int j = 0; j < offset; ++j) {
    char x;
    image.read(&x, sizeof(char));
    out.write(x);
}

image.seek(offset);
while (image.available()) {
    setRgb(image.size(), image.position());
    if (text.available()) {
        char text_byte = text.read();

        char x = 0x01;
        for (int i = 0; i < 8; ++i) {
        char img_byte;

            image.read(&img_byte, sizeof(char));
        char to_write;
            to_write = ((img_byte & 0xFE) | ((text_byte & x) >> i));
            x <<= 1;
      /*asm(
      //encrytp TO DO
      :::
      );*/
            out.write(to_write);
            
            if ((i + 1) % 3 == 0) {
                char x = image.read();
                out.write(x);
            }
        }
        char y = image.read();
        out.write(y);
    } else {
        char x = image.read();
        x &= 0xFE;
        out.write(x);
    }
}
}`

**Comment by r0n3-x** [comment]
`asm(
                "lds r24, (img_byte) \n"

                "lds r26, (text_byte) \n"

                "and r24, 0xFE \n"

                "and r24, 0x01 \n"

                "lds r25, (i) \n"

                "loop:"

                "lsr r26"

                "dec r25 \n"

                "brne loop \n"

                "or r24, r26 \n"

                "lds r28, (to_write) \n"

                "mov r28, r24 \n"
   
                :: :"r26", "r24", "r25", "r26"
                );
                x <<= 1;`
