### ISSUE TITLE
Codice Assembly Unveiling

### ISSUE THREAD

**Issue by SpaceCowboyS01** [SpaceCowboyS01/DekketScris#9]
Istruzioni Assembly per la decrittografia da implementare nel linguaggio C

- [x] Creazione del file .txt
- [x] Lettura dell'ultimo bit dal x-esimo byte dell'immagine
- [x] Costruzione del carattere con la sequenza di 8 bit
- [x] Scrittura del carattere nel .txt

**Comment by SpaceCowboyS01** [comment]
Il codice in C è funzionante, manca la raccolta dati dei test.
Il codice Assembly è quasi ultimato, attendo aggiornamenti.

**Comment by SpaceCowboyS01** [comment]
@MrError-404 
@Fede-2001 
Ciao ragazzi, potreste mettere in commit il codice che avete fatto?

**Comment by Fede-2001** [comment]
`void hiding(File image, File text, File out) {
    image.seek(10);
    int offset = 0;
    image.read(&offset, sizeof(offset));
    
    image.seek(0);
    for (int j = 0; j < offset; ++j) {
        char x;
        image.read(&x, sizeof(char));
        out.write(x);
    }

    image.seek(offset);
    while (image.available()) {
        setRgb(image.size() - offset, image.position());
        if (text.available()) {
            char text_byte = text.read();

            char x = 0x01;
            for (int i = 0; i < 8; ++i) {
                char img_byte;
                image.read(&img_byte, sizeof(char));
                char to_write = ((img_byte & 0xFE) | ((text_byte & x) >> i));
                x <<= 1;
                out.write(to_write);
                
                if ((i + 1) % 3 == 0) {
                    char x = image.read();
                    out.write(x);
                }
            }
            char y = image.read();
            out.write(y);
        } else {
            char x = image.read();
            x &= 0xFE;
            out.write(x);
        }
    }
}`
